.github/workflows/run_forklift_build_on_kind.yml, build_and_setup_everything_bazel.sh
- migrate the actions to bazel
- add GitHub cache
- disable download of forklift project in bash because the actions don't have rights for it and use actions/checkout instead
=> Migrate github actions to bazel build

.github/workflows/run_forklift_build_on_kind.yml, build_and_setup_everything_bazel.sh, build_and_setup_everything_bazel_manually.sh, ovirt/Dockerfile, ovirt/fakeovirt_deployment.yml, ovirt/forklift_provider.yml, ovirt/setup.sh, ovirt/stubs/clusters/content, ovirt/stubs/content, ovirt/stubs/datacenters/content, ovirt/stubs/diskprofiles/content, ovirt/stubs/disks/content, ovirt/stubs/events/content, ovirt/stubs/hosts/content, ovirt/stubs/networks/content, ovirt/stubs/storagedomains/content, ovirt/stubs/vms/content
Similar to https://github.com/kubev2v/forkliftci/pull/4
The patch does:
- setup of fakeovirt form quay.io/mnecas0/fakeovirt
- copy of the stubs to the new image which will be pushed to the local registry
- add the mocked provider to forklift
This patch is only for creating of providers not migrating of disks
=> Add ovirt init of fakeovirt with stubs

.github/workflows/run_forklift_build_on_kind.yml, build_and_setup_everything_bazel.sh, build_and_setup_everything_bazel_manually.sh, vmware/setup.sh, vmware/vcsim_deployment.yml, vmware/vsphere_provider.yml
Adding the vcsim for mocking the vsphere provider API. 
The patch does:
- setup of the vcsim deployment in the cluster
- setup k8s service so the controller can access the pod
- add the mocked provider to forklift
The vcsim is also used in the kubevirt CDI for testing the disk migration intself.
=> vcsim: init of vspehre provider tests

build_and_setup_everything_bazel.sh, build_and_setup_everything_bazel_manually.sh
We need to install kubevirt before the forklift so the operator sets up the default host provider
https://github.com/kubev2v/forklift/blob/f122b050fda71942a14cb8fb01613f3e2ded2928/operator/roles/forkliftcontroller/tasks/main.yml#L77-L81
=> Add default 'host' kubevirt provider

build_and_setup_everything_bazel.sh, build_and_setup_everything_bazel_manually.sh, kind-config.yaml, kind_with_registry.sh, ovirt/Dockerfile, ovirt/fakeovirt_deployment.yml, ovirt/forklift_provider.yml
This patch enables us to access the fakeovirt API from outside of the cluster.
It exposes it on `https://${NODE_IP}:30001/ovirt-engine/api`
=> Expose fakeovirt api to cluster node

k8s-deploy-kubevirt.sh, vmware/manual_deploy_migration_vsphere.yml, vmware/vsphere_provider.yml
introducing vddk-test-image  that is built by cdi [https://github.com/kubevirt/containerized-data-importer/tree/main/tools/vddk-test](url)
for our testing, it replaces the real vddk side-car container.
=> migrating VMs from vmware using vcsim and fake vddk.

.github/workflows/run_forklift_build_on_kind.yml, deploy_local_forklift_bazel.sh
GH-Actions is providing 2 Cores Only, with the default values we exceed that.
```Allocated resources:
203  (Total limits may be over 100 percent, i.e., overcommitted.)
204  Resource                       Requests      Limits
205  --------                       --------      ------
206  cpu                            1855m (92%)   1600m (80%)
207  memory                         3785Mi (54%)  2214Mi (31%)
```
Signed-off-by: Evgeny Slutsky <eslutsky@redhat.com>
=> Lower the CPU requests for PODs in our CI

build_forklift_bazel.sh
We used to take the latest and when when bazel released 6.0.0 it broke us. It's better to set a specific version so we won't break in such cases.
=> Set bazel version to 5.4.0

ovirt/ovirt_imageio_deployment.yml, ovirt/setup.sh
Deploying both fakeovirt and ovirt-imageio simultaneously saves some execution time compared to deploying them sequentially.
This PR also renames `imageio` to `ovirt-imageio` in several places.
=> Deploy fakeovirt and imageio simultaneously

deploy_local_forklift_bazel.sh
When forkliftci runs on GitHub hosted runners, we have a limit of 2 CPUs so we need to careful with the amount of CPUs we requests for forklift controllers, otherwise the importer pod(s) may not be able to start.
=> Lower requests.cpu values

k8s-deploy-kubevirt.sh
We have noticed frequent failures in getting the latest version of CDI but we lack information to debug it so here we store the JSON of the latest CDI version in a variable so it would be printed and also extract the tag_name using 'jq' instead of grep+sed
=> Refactor fetching latest CDI version

.github/workflows/run_forklift_build_on_kind.yml, action.yml, k8s-deploy-kubevirt.sh
Previously, we queried the latest version of CDI with an unauthenticated request from the command line using 'curl'. Frequently it failed with the following error:
"API rate limit exceeded ... (But here's the good news: Authenticated requests get a higer rate limit ..."
So here we change the way the latest version of CDI is queried. It is done using GitHub CLI with the access token from the GitHub repository. However, in order to keep the scripts working locally without setting an access token, there is a hard coded version that will be used when the CDI_VERSION variable is not set.
See #45
=> Get latest CDI version using GitHub CLI

build_and_setup_everything_bazel_manually.sh, kind_with_registry.sh
without this fix  kind_with_registry.sh wont be able to run correctly with remote docker
since it require kubectl we need to run setup_kind_sshtunnel before.
=> fix  running kind over remote docker

action.yml, deploy_local_forklift.sh
- Drop redundant specification of namespace
- Shorten 'Build and setup everything with bazel' step
=> Minor cleanups

install_kind.sh, kind_with_registry.sh
It was stored there by the action in github.com/kubev2v/forklift but that makes it a bit more complex for ones that want to execute the tests as forkliftci does locally, so from now on forkliftci would place it in /tmp instead of relying on doing it elsewhere.
=> Store kubeconfig in /tmp

cluster/kind/kind_with_registry.sh
follow-up for https://github.com/kubev2v/forkliftci/pull/21
=> disable kind LegacyServiceAccountTokenNoAutoGeneration on K8s>1.24 

build_and_setup_everything_bazel.sh, build_and_setup_everything_bazel_manually.sh, cluster/providers/install-provider.sh
this change alters the behavior when  CI installed manually (`build_and_setup_everything_bazel_manually.sh`):
- by default dont install any providers
- if ENV `PROVIDER_NAME` is set  then install  the provider  (all/ovirt/openstack/vsphere)
- optionally a provider can be installed separately by running 
`cluster/providers/install-provider.sh <all/ovirt/openstack/vsphere>`
=> separate provider installation script 

build_forklift_bazel.sh
this PR adds  2 new images for the CI localhost registry
- ovirt-populator-image 
- populator-controller-image
we are re-using Makefile build logic and wrap it from build_forklift_bazel.sh
=> Build image populator for ovirt

cluster/providers/utils/deploy_csi_driver_nfs.sh
In NFS-CSI 4.2.0, the permission changed to '0'. This breaks our CI as it expect the previous '0777'.
=> Add permissions to NFS directories

build_and_setup_everything_bazel.sh, cluster/providers/openstack/manifests/packstack_deployment.yml, cluster/providers/openstack/setup.sh, cluster/providers/openstack/utils.sh
packstack installation doesn't support built-in SSL/keystone deployment , so we add it at as Apache configuration .
internally all the openstack components  communicate with keystone on http/5000 , we add additional secure keystone on https/5001 - for external authentication
=> add keystone secure ssl service on port 5001

cluster/kind/kind_with_registry.sh
enable outside connection to the keystone  nodeport, so we could  connect to it from outside of the cluster.
=> expose packstack keystone port in kind

build_and_setup_everything_bazel.sh
disable keystone ssl  by default as it require too much memory from  gh-hosted runners (per PR tests).
=> openstack dont enable keystone  ssl by default

build_forklift_bazel.sh
For consistency, use the new bazel targets that were added:
push-openstack-populator
push-ovirt-populator
push-populator-controller
=> Use new bazel targets

stub-images/vddk-test-vmdk/BUILD.bazel
forklift-controller is about to check the validity of the VDDK image by existence of opt/vmware-vix-disklib-distrib/lib64/libvixDiskLib.so and therefore the stub image of VDDK that is used in our tests needs to have it.
=> Make a "valid" VDDK init image

cluster/common.sh
CDI started to enforce non-nil value for this field in v1.58.2, therefore setting this field to 'Filesystem'
=> add volumeMode to the standard storage profile

cluster/providers/vmware/vcsim_deployment.yml, cluster/providers/vmware/vcsim_deployment.yml.debug
Recently, a new tag was added to docker.io/vmware/vcsim, which caused one of the vSphere tests to fail. This change uses the previous tag instead of the latest and ensures the CI remains stable regardless of new changes.
=> Use a specific version of docker.io/vmware/vcsim so the CI won't break.
